services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
